Sem3OnlineHealthInsuranceMgmt/Models/Company.cs
using System.ComponentModel.DataAnnotations;

namespace Sem3OnlineHealthInsuranceMgmt.Models;

public class Company
{
    public int Id { get; set; }
    [Required]
    public string Name {get; set;}
    public string? StreetAddress {get; set;}
    public string? City {get; set;}
    public string? State {get; set;}
    public string? PostalCode {get; set;}
    public string? PhoneNumber {get; set;}
}

Sem3OnlineHealthInsuranceMgmt/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sem3OnlineHealthInsuranceMgmt.Models;
using Sem3OnlineHealthInsuranceMgmt.Repository.IRepository;
using Sem3OnlineHealthInsuranceMgmt.Utilities;
using Sem3OnlineHealthInsuranceMgmt.ViewModels;

namespace Sem3OnlineHealthInsuranceMgmt.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CompanyController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
        
        return View(objCompanyList);
    }

    public IActionResult Upsert(int? id)
    {
        if (id == null || id == 0)
        {
            //create
            return View(new Company());
        }
        else
        {
            //update
            Company companyObj = _unitOfWork.Company.Get(u=>u.Id==id);
            return View(companyObj);
        }
    }

    [HttpPost]
    public IActionResult Upsert(Company CompanyObj)
    {
        if (ModelState.IsValid)
        {
            if (CompanyObj.Id == 0)
            {
                _unitOfWork.Company.Add(CompanyObj);
            }
            else
            {
                _unitOfWork.Company.Update(CompanyObj);
            }
            _unitOfWork.Save();
            TempData["success"] = "Company created successfully.";
            return RedirectToAction("Index");   
        }
        else
        {
            return View(CompanyObj);
        }
    }


    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
        return Json(new { data = objCompanyList });
    }

    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var CompanyToBeDelete = _unitOfWork.Company.Get(u => u.Id == id);
        if (CompanyToBeDelete == null)
        {
            return Json(new {success = false, message = "Error while deleting."});
        }
        _unitOfWork.Company.Remove(CompanyToBeDelete);
        _unitOfWork.Save();
        
        return Json(new { success = true, message = "Delete successfully." });
    }

    #endregion
    
}

Sem3OnlineHealthInsuranceMgmt/Areas/Admin/Controllers/InsuranceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sem3OnlineHealthInsuranceMgmt.Models;
using Sem3OnlineHealthInsuranceMgmt.Repository.IRepository;
using Sem3OnlineHealthInsuranceMgmt.Utilities;
using Sem3OnlineHealthInsuranceMgmt.ViewModels;

namespace Sem3OnlineHealthInsuranceMgmt.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class InsuranceController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public InsuranceController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }

    public IActionResult Index()
    {
        List<Insurance> objInsuranceList = _unitOfWork.Insurance.GetAll(includeProperties:"Category").ToList();
        
        return View(objInsuranceList);
    }

    public IActionResult Upsert(int? id)
    {
        InsuranceVM insuranceVM = new()
        {
            CategoryList = _unitOfWork.Category
                .GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
            Insurance = new Insurance()
        };
        if (id == null || id == 0)
        {
            //create
            return View(insuranceVM);
        }
        else
        {
            //update
            insuranceVM.Insurance = _unitOfWork.Insurance.Get(u=>u.Id==id);
            return View(insuranceVM);
        }
    }

    [HttpPost]
    public IActionResult Upsert(InsuranceVM insuranceVM, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string insurancePath = Path.Combine(wwwRootPath, @"images/insurance");

                if (!string.IsNullOrEmpty(insuranceVM.Insurance.ImageUrl))
                {
                    //delete image
                    var oldImagePath = Path.Combine(wwwRootPath, insuranceVM.Insurance.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                
                using (var fileStrem = new FileStream(Path.Combine(insurancePath, fileName),FileMode.Create))
                {
                    file.CopyTo(fileStrem);
                }
                insuranceVM.Insurance.ImageUrl = @"/images/insurance/" + fileName;
            }

            if (insuranceVM.Insurance.Id == 0)
            {
                _unitOfWork.Insurance.Add(insuranceVM.Insurance);
            }
            else
            {
                _unitOfWork.Insurance.Update(insuranceVM.Insurance);
            }
            _unitOfWork.Save();
            TempData["success"] = "Insurance created successfully.";
            return RedirectToAction("Index");   
        }
        else
        {
            insuranceVM.CategoryList = _unitOfWork.Category
                .GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
            return View(insuranceVM);
        }
    }

    // public IActionResult Delete(int? id)
    // {
    //     if (id == null || id == 0)
    //     {
    //         return NotFound();
    //     }
    //     Insurance? insuranceFromDb = _unitOfWork.Insurance.Get(u => u.Id == id );
    //     if (insuranceFromDb == null)
    //     {
    //         return NotFound();
    //     }
    //     return View(insuranceFromDb);
    // }
    //
    // [HttpPost, ActionName("Delete")]
    // public IActionResult DeletePOST(int? id)
    // {
    //     Insurance? obj = _unitOfWork.Insurance.Get(u => u.Id == id );
    //     if (obj == null)
    //     {
    //         return NotFound();
    //     }
    //     _unitOfWork.Insurance.Remove(obj);
    //     _unitOfWork.Save();
    //     TempData["success"] = "Insurance delete successfully.";
    //     return RedirectToAction("Index");
    // }

    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        List<Insurance> objInsuranceList = _unitOfWork.Insurance.GetAll(includeProperties:"Category").ToList();
        return Json(new { data = objInsuranceList });
    }

    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var insuranceToBeDelete = _unitOfWork.Insurance.Get(u => u.Id == id);
        if (insuranceToBeDelete == null)
        {
            return Json(new {success = false, message = "Error while deleting insurance."});
        }
        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, insuranceToBeDelete.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Insurance.Remove(insuranceToBeDelete);
        _unitOfWork.Save();
        List<Insurance> objInsuranceList = _unitOfWork.Insurance.GetAll(includeProperties:"Category").ToList();
        return Json(new { data = objInsuranceList });
    }

    #endregion
    
}

Sem3OnlineHealthInsuranceMgmt/Areas/Admin/Views/Company/Delete.cshtml
@model Insurance

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Insurance</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" disabled class="form-control border-0 shadow"/>
                    <label asp-for="Title" class="ms-2" ></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" disabled class="form-control border-0 shadow"/>
                    <label asp-for="Description" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="PolicyNumber" disabled class="form-control border-0 shadow"/>
                    <label asp-for="PolicyNumber" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ResponsibleUnit" disabled class="form-control border-0 shadow"/>
                    <label asp-for="ResponsibleUnit" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" disabled class="form-control border-0 shadow"/>
                    <label asp-for="ListPrice" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" disabled class="form-control border-0 shadow"/>
                    <label asp-for="Price" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price50" disabled class="form-control border-0 shadow"/>
                    <label asp-for="Price50" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price100" disabled class="form-control border-0 shadow"/>
                    <label asp-for="Price100" class="ms-2"></label>
                </div> 
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Insurance" asp-action="Index" class="btn btn-secondary border form-control">
                            Back to List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Sem3OnlineHealthInsuranceMgmt/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Company List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
               
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Create new Company
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped" style="width: 100%">
            <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Phone Number</th>
                <th></th>
            </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
}

Sem3OnlineHealthInsuranceMgmt/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id!=0?"Update":"Create") Company</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden/>
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        @* <div asp-validation-summary="ModelOnly"></div> *@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow"/>
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow"/>
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" class="form-control border-0 shadow"/>
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow"/>
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow"/>
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow"/>
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" asp-action="Index" class="btn btn-secondary border form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}